---
- name: "Verify satellite_content_view_version_cleanup_keep is set"
  assert:
    that:
      - satellite_content_view_version_cleanup_keep|int >= 0
    fail_msg: "satellite_content_view_version_cleanup_keep needs to be set to >= 0"

- name: "Find all content views"
  redhat.satellite.resource_info:
    server_url: "{{ satellite_server_url | default(omit) }}"
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    resource: content_views
    search: "{{ satellite_content_view_version_cleanup_search | default(omit) }}"
  register: all_cvs

- name: "Delete unused composite content view versions"
  include_tasks: delete_cv_versions.yml
  vars:
    cv_name: "{{ ccv.name }}"
    cv_versions: "{{ (ccv.versions | rejectattr('environment_ids') | map(attribute='version') | map('float') | sort
      | map('string') | reverse | list)[satellite_content_view_version_cleanup_keep:] }}"
  loop: "{{ all_cvs.resources | selectattr('composite') | list }}"
  loop_control:
    label: "{{ ccv.label }}"
    loop_var: "ccv"
  when: (ccv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[satellite_content_view_version_cleanup_keep:]

- name: "Find and delete unused content view versions"
  include_tasks: find_and_delete_unused_cv_versions.yml
  loop: "{{ all_cvs.resources | rejectattr('composite') | list }}"
  loop_control:
    label: "{{ cv.label }}"
    loop_var: "cv"
  when: (cv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[satellite_content_view_version_cleanup_keep:]
