---
- name: "Subscription Manifest"
  include_role:
    name: redhat.satellite.manifest

- name: "Enable RHEL7 repository"
  include_role:
    name: redhat.satellite.repositories
  vars:
    satellite_products:
      - name: Red Hat Enterprise Linux Server
        repository_sets:
          - name: Red Hat Enterprise Linux 7 Server (RPMs)
            basearch: x86_64
            releasever: 7Server
  when: satellite_content_rhel_enable_rhel7

- name: "Enable RHEL8 repositories"
  include_role:
    name: redhat.satellite.repositories
  vars:
    satellite_products:
      - name: Red Hat Enterprise Linux for x86_64
        repository_sets:
          - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
            releasever: "{{ satellite_content_rhel_rhel8_releasever }}"
          - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
            releasever: "{{ satellite_content_rhel_rhel8_releasever }}"
  when: satellite_content_rhel_enable_rhel8

- name: "Sync RHEL7 repository"
  redhat.satellite.repository_sync:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    product: Red Hat Enterprise Linux Server
  async: 14400
  poll: 0
  register: rhel7_sync
  when: satellite_content_rhel_enable_rhel7 and satellite_content_rhel_sync_now

- name: "Sync RHEL8 repositories"
  redhat.satellite.repository_sync:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    product: Red Hat Enterprise Linux for x86_64
  async: 14400
  poll: 0
  register: rhel8_sync
  when: satellite_content_rhel_enable_rhel8 and satellite_content_rhel_sync_now

- name: "Create Sync Plan"
  include_role:
    name: redhat.satellite.sync_plans
  vars:
    satellite_sync_plans:
      - name: "{{ satellite_sync_plan_name | default('RHEL Sync Plan') }}"
        interval: "{{ satellite_sync_plan_interval | default('daily') }}"
        cron_expression: "{{ satellite_sync_plan_cron_expression | default(omit) }}"
        sync_date: "{{ satellite_sync_plan_sync_date | default('2020-01-01 00:00:00 UTC') }}"
        products:
          "{{ [satellite_content_rhel_enable_rhel7 | ternary('Red Hat Enterprise Linux Server', ''),
          satellite_content_rhel_enable_rhel8 | ternary('Red Hat Enterprise Linux for x86_64', '')]
          | select() | list }}"

- name: "Create Activation Key"
  include_role:
    name: redhat.satellite.activation_keys
  vars:
    satellite_activation_keys:
      - name: "{{ satellite_activation_key_name | default('base_rhel_key') }}"
        description: "Generated by ansible role redhat.satellite.content_rhel"

- name: "Wait for RHEL7 sync completion"
  async_status:
    jid: "{{ rhel7_sync.ansible_job_id }}"
  register: rhel7_job_result
  until: rhel7_job_result.finished
  retries: 99999
  delay: 10
  when: satellite_content_rhel_enable_rhel7 and satellite_content_rhel_sync_now and satellite_content_rhel_wait_for_syncs

- name: "Wait for RHEL8 sync completion"
  async_status:
    jid: "{{ rhel8_sync.ansible_job_id }}"
  register: rhel8_job_result
  until: rhel8_job_result.finished
  retries: 99999
  delay: 10
  when: satellite_content_rhel_enable_rhel8 and satellite_content_rhel_sync_now and satellite_content_rhel_wait_for_syncs
